# Include only in the primary website HTTPS server.
location = /_events {
    access_log /var/log/pinmoo-events/events.log pinmoo_events if=$pinmoo_event_log;
    error_log /dev/null crit;
    add_header Cache-Control "no-store" always;
    add_header X-Robots-Tag "noindex, nofollow" always;
    if ($pinmoo_event_valid = 0) { return 400; }
    return 204;
}
