import {
  ArrowRight,
  BadgeCheck,
  BarChart3,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  CheckCircle2,
  ChevronDown,
  CircleUserRound,
  ClipboardList,
  Clock,
  FilePenLine,
  GraduationCap,
  Image,
  Layers,
  Leaf,
  Lightbulb,
  LineChart,
  MapPinned,
  Menu,
  MessageCircle,
  MessagesSquare,
  PackageCheck,
  Phone,
  PieChart,
  RefreshCw,
  Rocket,
  Search,
  Send,
  ShieldCheck,
  ShoppingBag,
  Store,
  Target,
  TrendingUp,
  Users,
  X,
  Zap
} from 'lucide-react';

const icons = {
  ArrowRight,
  BadgeCheck,
  BarChart3,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  CheckCircle2,
  ChevronDown,
  CircleUserRound,
  ClipboardList,
  Clock,
  FilePenLine,
  GraduationCap,
  Image,
  Layers,
  Leaf,
  Lightbulb,
  LineChart,
  MapPinned,
  Menu,
  MessageCircle,
  MessagesSquare,
  PackageCheck,
  Phone,
  PieChart,
  RefreshCw,
  Rocket,
  Search,
  Send,
  ShieldCheck,
  ShoppingBag,
  Store,
  Target,
  TrendingUp,
  Users,
  X,
  Zap
};

export function Icon({ name, size = 22, strokeWidth = 2.2, ...props }) {
  const Component = icons[name] || Target;
  return <Component size={size} strokeWidth={strokeWidth} aria-hidden="true" {...props} />;
}
